### PR TITLE
added lint config to package.json

### PR DESCRIPTION
**Pull request by ceogawa**
should be working !! :)

### CODE REVIEW

**Comment by artiwari07** [comment]
Great job !!

**Comment by ceogawa** [comment]
oops!

**Comment by ceogawa** [comment]
Thank you for merging and checking out the changes! @artiwari07 😄

**Comment by leah16303** [comment]
No comments. Looks great!

**Comment by ShafaySyed786** [comment]
Thanks for adding this! 🙏

**Pull request merged**
